FROM python:3.10.6-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY text_data text_data


CMD uvicorn text_data.api_file:app --host 0.0.0.0 --port $PORT
